In [1]:
import pandas as pd
import numpy as np

A continuacion realizo la lectura de los csv

In [2]:
penetracion_p100hab = pd.read_csv('./DatasetsObligatorios/Penetración-poblacion.csv')
penetracion_p100hab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Año                       984 non-null    int64
 1   Trimestre                 984 non-null    int64
 2   Provincia                 984 non-null    object
 3   Accesos por cada 100 hab  984 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 30.9+ KB

In [3]:
penetracion_pcia = pd.read_csv('./DatasetsObligatorios/Penetracion-hogares.csv')
penetracion_pcia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           984 non-null    int64
 1   Trimestre                     984 non-null    int64
 2   Provincia                     984 non-null    object
 3   Accesos por cada 100 hogares  984 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 30.9+ KB

In [4]:
accesos_baf = pd.read_csv('./DatasetsObligatorios/Totales Dial-BAf.csv')
accesos_baf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Año               41 non-null     int64
 1   Trimestre         41 non-null     int64
 2   Banda ancha fija  41 non-null     int64
 3   Dial up           41 non-null     int64
 4   Total             41 non-null     int64
 5   Periodo           41 non-null     object
dtypes: int64(5), object(1)
memory usage: 2.1+ KB

In [5]:
accesos_baf_pcia = pd.read_csv('./DatasetsObligatorios/Dial-BAf.csv')
accesos_baf_pcia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Año               984 non-null    int64
 1   Trimestre         984 non-null    int64
 2   Provincia         984 non-null    object
 3   Banda ancha fija  984 non-null    int64
 4   Dial up           982 non-null    float64
 5   Total             984 non-null    int64
dtypes: float64(1), int64(4), object(1)
memory usage: 46.3+ KB

In [6]:
accesos_tec = pd.read_csv('./DatasetsObligatorios/Accesos Por Tecnología.csv')
accesos_tec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           985 non-null    object
 1   Trimestre     985 non-null    object
 2   Provincia     984 non-null    object
 3   ADSL          984 non-null    float64
 4   Cablemodem    984 non-null    float64
 5   Fibra óptica  984 non-null    float64
 6   Wireless      984 non-null    float64
 7   Otros         984 non-null    float64
 8   Total         984 non-null    float64
dtypes: float64(6), object(3)
memory usage: 69.5+ KB

In [7]:
accesos_vmd = pd.read_csv('./DatasetsObligatorios/Totales VMD.csv')
accesos_vmd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     41 non-null     int64
 1   Trimestre               41 non-null     int64
 2   Mbps (Media de bajada)  41 non-null     float64
 3   Trimestre.1             41 non-null     object
dtypes: float64(1), int64(2), object(1)
memory usage: 1.4+ KB

In [8]:
accesos_vel_prov = pd.read_csv('./DatasetsObligatorios/Accesos por velocidad.csv')
accesos_vel_prov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Año                  984 non-null    int64
 1   Trimestre            984 non-null    int64
 2   Provincia            984 non-null    object
 3   HASTA 512 kbps       984 non-null    float64
 4   + 512 Kbps - 1 Mbps  984 non-null    float64
 5   + 1 Mbps - 6 Mbps    984 non-null    float64
 6   + 6 Mbps - 10 Mbps   984 non-null    float64
 7   + 10 Mbps - 20 Mbps  984 non-null    float64
 8   + 20 Mbps - 30 Mbps  984 non-null    float64
 9   + 30 Mbps            984 non-null    float64
 10  OTROS                978 non-null    float64
 11  Total                984 non-null    float64
dtypes: float64(9), int64(2), object(1)
memory usage: 92.4+ KB

In [9]:
accesos_totales = pd.read_csv('./DatasetsObligatorios/Totales Accesos por velocidad.csv')
accesos_totales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Año                      41 non-null     int64
 1   Trimestre                41 non-null     int64
 2   Hasta 512 kbps           41 non-null     int64
 3   Entre 512 Kbps y 1 Mbps  41 non-null     int64
 4   Entre 1 Mbps y 6 Mbps    41 non-null     int64
 5   Entre 6 Mbps y 10 Mbps   41 non-null     int64
 6   Entre 10 Mbps y 20 Mbps  41 non-null     int64
 7   Entre 20 Mbps y 30 Mbps  41 non-null     int64
 8   Más de 30 Mbps           41 non-null     int64
 9   OTROS                    41 non-null     int64
 10  Total                    41 non-null     int64
dtypes: int64(11)
memory usage: 3.7 KB

In [10]:
accesos_prov_vel = pd.read_csv('./DatasetsObligatorios/Velocidad_sin_Rangos.csv')
accesos_prov_vel.head()

,Año,Trimestre,Provincia,Otros,"0,256 Mbps","0,375 Mbps","0,625 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",...,2048 Mbps,2529 Mbps,3072 Mbps,4000 Mbps,5000 Mbps,5125 Mbps,6000 Mbps,7000 Mbps,8000 Mbps,10000 Mbps
0,2024.0,1.0,Buenos Aires,125147.0,18.0,0.0,0.0,25815.0,169.0,4611.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024.0,1.0,Capital Federal,0.0,31.0,0.0,0.0,451.0,34.0,1307.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024.0,1.0,Catamarca,70.0,0.0,0.0,0.0,34.0,37.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2024.0,1.0,Chaco,3816.0,0.0,0.0,0.0,234.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024.0,1.0,Chubut,16640.0,8.0,0.0,0.0,69.0,34.0,836.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
ingresos = pd.read_csv('./DatasetsObligatorios/Ingresos .csv')
ingresos.head()

    Año  Trimestre  Ingresos (miles de pesos)        Periodo
0  2024          1               2.804191e+08   Ene-Mar 2024
1  2023          4               1.673760e+08   Oct-Dic 2023
2  2023          3               1.331066e+08  Jul-Sept 2023
3  2023          2               1.180603e+08   Jun-Mar 2023
4  2033          1               1.041350e+08   Ene-Mar 2023

In [12]:
accesos_loc = pd.read_csv('./DatasetsObligatorios/Acc_vel_loc_sinrangos.csv')
accesos_loc.head()

,Provincia,Partido,Localidad,Link Indec,Otros,"0,256 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",1 Mbps,...,680 Mbps,700 Mbps,800 Mbps,850 Mbps,900 Mbps,999 Mbps,1000 Mbps,1024 Mbps,4000 Mbps,10000 Mbps
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,NaN,NaN,2.0,NaN,19.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BUENOS AIRES,25 de Mayo,Agustín Mosconi,6854010,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BUENOS AIRES,25 de Mayo,Del Valle,6854020,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BUENOS AIRES,25 de Mayo,Ernestina,6854030,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
acceso_tec_loc = pd.read_csv('./DatasetsObligatorios/Accesos_tecnologia_localidad.csv')
acceso_tec_loc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3352 entries, 0 to 3351
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      3072 non-null   object
 1   Partido        3072 non-null   object
 2   Localidad      3072 non-null   object
 3   Link Indec     3072 non-null   object
 4   ADSL           3352 non-null   int64
 5   CABLEMODEM     3352 non-null   int64
 6   DIAL UP        3352 non-null   int64
 7   FIBRA OPTICA   3352 non-null   int64
 8   OTROS          3352 non-null   int64
 9   SATELITAL      3352 non-null   int64
 10  WIMAX          3352 non-null   int64
 11  WIRELESS       3352 non-null   int64
 12  Total general  3352 non-null   int64
dtypes: int64(9), object(4)
memory usage: 340.6+ KB

In [14]:
mapa_conect = pd.read_csv('./DatasetsObligatorios/mapa_conectividad.csv')
mapa_conect.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4305 entries, 0 to 4304
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Provincia       4305 non-null   object
 1   Partido         4305 non-null   object
 2   Localidad       4305 non-null   object
 3   Población       4305 non-null   int64
 4   ADSL            4305 non-null   object
 5   Cablemódem      4305 non-null   object
 6   Dial Up         4305 non-null   object
 7   Fibra óptica    4305 non-null   object
 8   Satelital       4305 non-null   object
 9   Wireless        4305 non-null   object
 10  Telefonía Fija  4305 non-null   object
 11  3G              4305 non-null   object
 12  4G              4305 non-null   object
 13  Link            4293 non-null   float64
 14  Latitud         4305 non-null   float64
 15  Longitud        4305 non-null   float64
dtypes: float64(3), int64(1), object(12)
memory usage: 538.3+ KB

In [15]:
#Combino columnas año, Trimestre, Provincia
df1_comb = pd.merge(penetracion_p100hab, penetracion_pcia, on =['Año', 'Trimestre','Provincia'])
df1_comb.sample(5)

,Año,Trimestre,Provincia,Accesos por cada 100 hab,Accesos por cada 100 hogares
342,2020,3,Corrientes,10.993614,41.750749
970,2014,1,La Pampa,15.994062,48.425321
410,2019,4,Catamarca,9.268865,36.438429
187,2022,2,Santa Cruz,12.839623,43.150000
423,2019,4,Río Negro,17.133870,55.705010

In [16]:
accesos_tec.head(5)

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2024,1,Buenos Aires,203297.0,2790663.0,1799013.0,150290.0,101294.0,5044557.0
1,2024,1,Capital Federal,70108.0,1177475.0,203756.0,4493.0,48879.0,1504711.0
2,2024,1,Catamarca,5901.0,11025.0,56542.0,1384.0,81.0,74933.0
3,2024,1,Chaco,11343.0,58929.0,64463.0,8404.0,12404.0,155543.0
4,2024,1,Chubut,26306.0,77217.0,26356.0,30867.0,9930.0,170676.0

In [17]:
accesos_tec.dtypes

Año              object
Trimestre        object
Provincia        object
ADSL            float64
Cablemodem      float64
Fibra óptica    float64
Wireless        float64
Otros           float64
Total           float64
dtype: object

In [18]:
accesos_tec.isna().sum()

Año             1
Trimestre       1
Provincia       2
ADSL            2
Cablemodem      2
Fibra óptica    2
Wireless        2
Otros           2
Total           2
dtype: int64

In [19]:
accesos_tec = accesos_tec.dropna()

In [20]:
accesos_tec.info()

<class 'pandas.core.frame.DataFrame'>
Index: 984 entries, 0 to 983
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           984 non-null    object
 1   Trimestre     984 non-null    object
 2   Provincia     984 non-null    object
 3   ADSL          984 non-null    float64
 4   Cablemodem    984 non-null    float64
 5   Fibra óptica  984 non-null    float64
 6   Wireless      984 non-null    float64
 7   Otros         984 non-null    float64
 8   Total         984 non-null    float64
dtypes: float64(6), object(3)
memory usage: 76.9+ KB

In [21]:
#visualizo el Dataframe y encuentro '*' en Año y Trimestre. Reemplazo el *
access_tec = accesos_tec.copy()
access_tec['Año'].unique() 
access_tec['Año'] = access_tec['Año'].str.replace('[^0-9]', '').str.rstrip('*')
access_tec['Año'] = access_tec['Año'].astype(int)
#access_tec.head(5)
access_tec['Año'].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014])

In [22]:
# Convertir las columnas a enteros
accesos_tec = accesos_tec[['ADSL', 'Cablemodem', 'Wireless', 'Otros', 'Total', 'Fibra óptica']] = accesos_tec[['ADSL', 'Cablemodem', 'Wireless', 'Otros', 'Total', 'Fibra óptica']].astype(int)

In [23]:
access_tec['Trimestre'] = access_tec['Trimestre'].str.replace('[^0-9]', '').str.rstrip('*')
access_tec['Trimestre'] = access_tec['Trimestre'].astype(int)

In [24]:
access_tec['Trimestre'].unique()

array([1, 4, 3, 2])

In [25]:
access_tec.info()

<class 'pandas.core.frame.DataFrame'>
Index: 984 entries, 0 to 983
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           984 non-null    int32
 1   Trimestre     984 non-null    int32
 2   Provincia     984 non-null    object
 3   ADSL          984 non-null    float64
 4   Cablemodem    984 non-null    float64
 5   Fibra óptica  984 non-null    float64
 6   Wireless      984 non-null    float64
 7   Otros         984 non-null    float64
 8   Total         984 non-null    float64
dtypes: float64(6), int32(2), object(1)
memory usage: 69.2+ KB

In [26]:
# Combino el df previo creado con las mismas columnas
df2_comb = pd.merge(access_tec, df1_comb, on=['Año', 'Trimestre', 'Provincia'])
df2_comb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           984 non-null    int32
 1   Trimestre                     984 non-null    int32
 2   Provincia                     984 non-null    object
 3   ADSL                          984 non-null    float64
 4   Cablemodem                    984 non-null    float64
 5   Fibra óptica                  984 non-null    float64
 6   Wireless                      984 non-null    float64
 7   Otros                         984 non-null    float64
 8   Total                         984 non-null    float64
 9   Accesos por cada 100 hab      984 non-null    float64
 10  Accesos por cada 100 hogares  984 non-null    float64
dtypes: float64(8), int32(2), object(1)
memory usage: 77.0+ KB

In [27]:
df2_comb[['ADSL', 'Cablemodem', 'Wireless', 'Otros', 'Total', 'Fibra óptica', 'Accesos por cada 100 hab']] = df2_comb[['ADSL', 'Cablemodem', 'Wireless', 'Otros', 'Total', 'Fibra óptica', 'Accesos por cada 100 hab']].astype(int)

In [28]:
#Unifico DF con el mismo tipo de informacion.
df3_comb = pd.merge(df2_comb, accesos_baf_pcia, on=['Año', 'Trimestre', 'Provincia'])
df3_comb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           984 non-null    int32
 1   Trimestre                     984 non-null    int32
 2   Provincia                     984 non-null    object
 3   ADSL                          984 non-null    int32
 4   Cablemodem                    984 non-null    int32
 5   Fibra óptica                  984 non-null    int32
 6   Wireless                      984 non-null    int32
 7   Otros                         984 non-null    int32
 8   Total_x                       984 non-null    int32
 9   Accesos por cada 100 hab      984 non-null    int32
 10  Accesos por cada 100 hogares  984 non-null    float64
 11  Banda ancha fija              984 non-null    int64
 12  Dial up                       982 non-null    float64
 13  Total_y                       984 non-null    int64
dtypes: float64(2), int32(9), int64(2), object(1)
memory usage: 73.2+ KB

In [29]:
df3_comb['Total_y'] = df3_comb['Total_y'].astype(int)

In [30]:
df4_comb = pd.merge(df3_comb, accesos_vel_prov, on=['Año', 'Trimestre', 'Provincia'])
df4_comb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           960 non-null    int32
 1   Trimestre                     960 non-null    int32
 2   Provincia                     960 non-null    object
 3   ADSL                          960 non-null    int32
 4   Cablemodem                    960 non-null    int32
 5   Fibra óptica                  960 non-null    int32
 6   Wireless                      960 non-null    int32
 7   Otros                         960 non-null    int32
 8   Total_x                       960 non-null    int32
 9   Accesos por cada 100 hab      960 non-null    int32
 10  Accesos por cada 100 hogares  960 non-null    float64
 11  Banda ancha fija              960 non-null    int64
 12  Dial up                       958 non-null    float64
 13  Total_y                       960 non-null    int32
 14  HASTA 512 kbps                960 non-null    float64
 15  + 512 Kbps - 1 Mbps           960 non-null    float64
 16  + 1 Mbps - 6 Mbps             960 non-null    float64
 17  + 6 Mbps - 10 Mbps            960 non-null    float64
 18  + 10 Mbps - 20 Mbps           960 non-null    float64
 19  + 20 Mbps - 30 Mbps           960 non-null    float64
 20  + 30 Mbps                     960 non-null    float64
 21  OTROS                         954 non-null    float64
 22  Total                         960 non-null    float64
dtypes: float64(11), int32(10), int64(1), object(1)
memory usage: 135.1+ KB

In [31]:
df_nac = pd.merge(accesos_baf, accesos_vmd, on=['Año', 'Trimestre'])
df_nac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     41 non-null     int64
 1   Trimestre               41 non-null     int64
 2   Banda ancha fija        41 non-null     int64
 3   Dial up                 41 non-null     int64
 4   Total                   41 non-null     int64
 5   Periodo                 41 non-null     object
 6   Mbps (Media de bajada)  41 non-null     float64
 7   Trimestre.1             41 non-null     object
dtypes: float64(1), int64(5), object(2)
memory usage: 2.7+ KB

In [32]:
df2_nac = pd.merge(df_nac, accesos_totales, on =['Año', 'Trimestre'])
df3_nac = pd.merge(df2_nac, ingresos, on =['Año', 'Trimestre'])
df4_nac = pd.merge(df3_nac, access_tec, on =['Año', 'Trimestre'])

In [33]:
df4_nac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Año                        960 non-null    int64
 1   Trimestre                  960 non-null    int64
 2   Banda ancha fija           960 non-null    int64
 3   Dial up                    960 non-null    int64
 4   Total_x                    960 non-null    int64
 5   Periodo_x                  960 non-null    object
 6   Mbps (Media de bajada)     960 non-null    float64
 7   Trimestre.1                960 non-null    object
 8   Hasta 512 kbps             960 non-null    int64
 9   Entre 512 Kbps y 1 Mbps    960 non-null    int64
 10  Entre 1 Mbps y 6 Mbps      960 non-null    int64
 11  Entre 6 Mbps y 10 Mbps     960 non-null    int64
 12  Entre 10 Mbps y 20 Mbps    960 non-null    int64
 13  Entre 20 Mbps y 30 Mbps    960 non-null    int64
 14  Más de 30 Mbps             960 non-null    int64
 15  OTROS                      960 non-null    int64
 16  Total_y                    960 non-null    int64
 17  Ingresos (miles de pesos)  960 non-null    float64
 18  Periodo_y                  960 non-null    object
 19  Provincia                  960 non-null    object
 20  ADSL                       960 non-null    float64
 21  Cablemodem                 960 non-null    float64
 22  Fibra óptica               960 non-null    float64
 23  Wireless                   960 non-null    float64
 24  Otros                      960 non-null    float64
 25  Total                      960 non-null    float64
dtypes: float64(8), int64(14), object(4)
memory usage: 195.1+ KB

In [34]:
df_partidos = pd.merge(acceso_tec_loc, mapa_conect, on = ['Provincia', 'Partido', 'Localidad'])
df_partidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2826 entries, 0 to 2825
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Provincia       2826 non-null   object
 1   Partido         2826 non-null   object
 2   Localidad       2826 non-null   object
 3   Link Indec      2826 non-null   object
 4   ADSL_x          2826 non-null   int64
 5   CABLEMODEM      2826 non-null   int64
 6   DIAL UP         2826 non-null   int64
 7   FIBRA OPTICA    2826 non-null   int64
 8   OTROS           2826 non-null   int64
 9   SATELITAL       2826 non-null   int64
 10  WIMAX           2826 non-null   int64
 11  WIRELESS        2826 non-null   int64
 12  Total general   2826 non-null   int64
 13  Población       2826 non-null   int64
 14  ADSL_y          2826 non-null   object
 15  Cablemódem      2826 non-null   object
 16  Dial Up         2826 non-null   object
 17  Fibra óptica    2826 non-null   object
 18  Satelital       2826 non-null   object
 19  Wireless        2826 non-null   object
 20  Telefonía Fija  2826 non-null   object
 21  3G              2826 non-null   object
 22  4G              2826 non-null   object
 23  Link            2823 non-null   float64
 24  Latitud         2826 non-null   float64
 25  Longitud        2826 non-null   float64
dtypes: float64(3), int64(10), object(13)
memory usage: 574.2+ KB

In [35]:
df2_partidos = pd.merge(df_partidos, accesos_loc, on = ['Provincia', 'Partido', 'Localidad'])
df2_partidos.head(5)

,Provincia,Partido,Localidad,Link Indec_x,ADSL_x,CABLEMODEM,DIAL UP,FIBRA OPTICA,OTROS,SATELITAL,...,680 Mbps,700 Mbps,800 Mbps,850 Mbps,900 Mbps,999 Mbps,1000 Mbps,1024 Mbps,4000 Mbps,10000 Mbps
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,755,4600,0,2,0,742,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BUENOS AIRES,25 de Mayo,Del Valle,6854020,181,0,0,0,10,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BUENOS AIRES,25 de Mayo,Norberto de la Riestra,6854060,0,782,0,496,16,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BUENOS AIRES,25 de Mayo,Lucas Monteverde,6854050,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
pd.set_option('display.max_columns', None)
df2_partidos.head(5)

,Provincia,Partido,Localidad,Link Indec_x,ADSL_x,CABLEMODEM,DIAL UP,FIBRA OPTICA,OTROS,SATELITAL,WIMAX,WIRELESS,Total general,Población,ADSL_y,Cablemódem,Dial Up,Fibra óptica,Satelital,Wireless,Telefonía Fija,3G,4G,Link,Latitud,Longitud,Link Indec_y,Otros,"0,256 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",1 Mbps,"1,5 Mbps",2 Mbps,"2,2 Mbps","2,5 Mbps",3 Mbps,"3,3 Mbps","3,5 Mbps",4 Mbps,"4,5 Mbps",5 Mbps,6 Mbps,"6,4 Mbps",7 Mbps,"7,5 Mbps",8 Mbps,9 Mbps,10 Mbps,"10,1 Mbps","10,2 Mbps",11 Mbps,12 Mbps,"12,3 Mbps",13 Mbps,14 Mbps,15 Mbps,16 Mbps,17 Mbps,18 Mbps,20 Mbps,"20,5 Mbps",21 Mbps,22 Mbps,23 Mbps,24 Mbps,25 Mbps,"25,1 Mbps","25,5 Mbps",26 Mbps,27 Mbps,30 Mbps,31 Mbps,32 Mbps,35 Mbps,36 Mbps,40 Mbps,41 Mbps,45 Mbps,48 Mbps,49 Mbps,50 Mbps,"50,1 Mbps","50,25 Mbps",51 Mbps,55 Mbps,59 Mbps,60 Mbps,61 Mbps,65 Mbps,66 Mbps,70 Mbps,75 Mbps,80 Mbps,85 Mbps,90 Mbps,95 Mbps,98 Mbps,100 Mbps,"100,1 Mbps","100,25 Mbps",105 Mbps,110 Mbps,120 Mbps,122 Mbps,125 Mbps,130 Mbps,140 Mbps,150 Mbps,155 Mbps,160 Mbps,164 Mbps,165 Mbps,180 Mbps,200 Mbps,205 Mbps,212 Mbps,220 Mbps,225 Mbps,240 Mbps,246 Mbps,250 Mbps,256 Mbps,275 Mbps,300 Mbps,320 Mbps,325 Mbps,330 Mbps,350 Mbps,400 Mbps,450 Mbps,480 Mbps,500 Mbps,512 Mbps,520 Mbps,540 Mbps,600 Mbps,680 Mbps,700 Mbps,800 Mbps,850 Mbps,900 Mbps,999 Mbps,1000 Mbps,1024 Mbps,4000 Mbps,10000 Mbps
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,755,4600,0,2,0,742,0,727,6826,23408,SI,SI,--,--,SI,SI,SI,SI,SI,6854100.0,-35.433939,-60.173121,6854100,NaN,NaN,2.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,85.0,NaN,145.0,NaN,NaN,NaN,76.0,NaN,NaN,NaN,299.0,NaN,288.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,415.0,NaN,NaN,NaN,1797.0,NaN,NaN,NaN,NaN,NaN,144.0,NaN,NaN,NaN,NaN,1501.0,NaN,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,647.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,693.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BUENOS AIRES,25 de Mayo,Del Valle,6854020,181,0,0,0,10,1,0,0,192,899,SI,--,--,--,SI,--,--,SI,--,6854020.0,-35.897345,-60.731609,6854020,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,0,0,0,0,0,0,0,181,181,547,--,--,--,--,--,SI,--,--,--,6854040.0,-35.164397,-60.081358,6854040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.0,NaN,NaN,3.0,NaN,NaN,56.0,NaN,7.0,3.0,NaN,NaN,NaN,4.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BUENOS AIRES,25 de Mayo,Norberto de la Riestra,6854060,0,782,0,496,16,0,0,185,1479,4524,--,SI,--,SI,--,SI,SI,SI,SI,6854060.0,-35.272779,-59.771933,6854060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.0,NaN,NaN,32.0,NaN,NaN,9.0,NaN,8.0,914.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,322.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BUENOS AIRES,25 de Mayo,Lucas Monteverde,6854050,0,0,0,0,0,0,0,6,6,63,--,--,--,--,--,SI,--,--,--,6854050.0,-35.483827,-59.988065,6854050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Para finalizar, me encuentro con 3 DF con la informacion que necesito, los cuales son:
df4_comb, df4_nac, df2_partidos,

In [37]:
# Evaluo los resultados del trabajo
igual_1 = (df4_comb['Total'] == df4_comb['Total_x']).sum()
igual_2 = (df4_comb['Total'] == df4_comb['Total_y']).sum()
igual_3 = (df4_comb['Total_x'] == df4_comb['Total_y']).sum()

print(igual_1)
print(igual_2)
print(igual_3)

439
439
960

Sumando las conexiones, Total_x y Total_y difieren en el resultado de la suma de los Mbps, decido eliminar la ultima columna

In [38]:
df4_comb = df4_comb.drop('Total_y', axis=1)
df4_comb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           960 non-null    int32
 1   Trimestre                     960 non-null    int32
 2   Provincia                     960 non-null    object
 3   ADSL                          960 non-null    int32
 4   Cablemodem                    960 non-null    int32
 5   Fibra óptica                  960 non-null    int32
 6   Wireless                      960 non-null    int32
 7   Otros                         960 non-null    int32
 8   Total_x                       960 non-null    int32
 9   Accesos por cada 100 hab      960 non-null    int32
 10  Accesos por cada 100 hogares  960 non-null    float64
 11  Banda ancha fija              960 non-null    int64
 12  Dial up                       958 non-null    float64
 13  HASTA 512 kbps                960 non-null    float64
 14  + 512 Kbps - 1 Mbps           960 non-null    float64
 15  + 1 Mbps - 6 Mbps             960 non-null    float64
 16  + 6 Mbps - 10 Mbps            960 non-null    float64
 17  + 10 Mbps - 20 Mbps           960 non-null    float64
 18  + 20 Mbps - 30 Mbps           960 non-null    float64
 19  + 30 Mbps                     960 non-null    float64
 20  OTROS                         954 non-null    float64
 21  Total                         960 non-null    float64
dtypes: float64(11), int32(9), int64(1), object(1)
memory usage: 131.4+ KB

In [39]:
df_agrupado = df4_comb.groupby(['Año', 'Trimestre', 'Provincia']).sum()
df_agrupado.sample(5)

                                      ADSL  Cablemodem  Fibra óptica  \
Año  Trimestre Provincia
2022 3         Capital Federal      140791     1240125        129218
2020 2         Catamarca             26968        3641         14878
2021 4         Santiago Del Estero   19032       86563          1088
2017 4         Misiones              56271       47470            95
     3         Córdoba              344580      319360         10579

                                    Wireless  Otros  Total_x  \
Año  Trimestre Provincia
2022 3         Capital Federal          5758  31787  1547679
2020 2         Catamarca                 261   2228    47976
2021 4         Santiago Del Estero      6256   2922   115861
2017 4         Misiones                    5     54   103895
     3         Córdoba                  7137  14988   696644

                                    Accesos por cada 100 hab  \
Año  Trimestre Provincia
2022 3         Capital Federal                            50
2020 2         Catamarca                                  11
2021 4         Santiago Del Estero                        11
2017 4         Misiones                                    8
     3         Córdoba                                    19

                                    Accesos por cada 100 hogares  \
Año  Trimestre Provincia
2022 3         Capital Federal                        122.280000
2020 2         Catamarca                               45.431818
2021 4         Santiago Del Estero                     47.045949
2017 4         Misiones                                31.142185
     3         Córdoba                                 62.307002

                                    Banda ancha fija  Dial up  HASTA 512 kbps  \
Año  Trimestre Provincia
2022 3         Capital Federal               1545534   2145.0           517.0
2020 2         Catamarca                       47975      1.0            63.0
2021 4         Santiago Del Estero            115859      2.0           178.0
2017 4         Misiones                       103895      0.0          1053.0
     3         Córdoba                        696536    108.0           327.0

                                    + 512 Kbps - 1 Mbps  + 1 Mbps - 6 Mbps  \
Año  Trimestre Provincia
2022 3         Capital Federal                   5742.0            34371.0
2020 2         Catamarca                            0.0             8801.0
2021 4         Santiago Del Estero                909.0            31915.0
2017 4         Misiones                          3900.0            41723.0
     3         Córdoba                          26154.0           309161.0

                                    + 6 Mbps - 10 Mbps  + 10 Mbps - 20 Mbps  \
Año  Trimestre Provincia
2022 3         Capital Federal                 67829.0              51946.0
2020 2         Catamarca                        8690.0              10242.0
2021 4         Santiago Del Estero             61524.0              12205.0
2017 4         Misiones                        23131.0              22262.0
     3         Córdoba                        100113.0             189302.0

                                    + 20 Mbps - 30 Mbps  + 30 Mbps     OTROS  \
Año  Trimestre Provincia
2022 3         Capital Federal                  28692.0  1253105.0  105477.0
2020 2         Catamarca                          426.0    16578.0    3176.0
2021 4         Santiago Del Estero                800.0     7537.0     793.0
2017 4         Misiones                          9091.0     2735.0       0.0
     3         Córdoba                          38131.0    16741.0       0.0

                                        Total
Año  Trimestre Provincia
2022 3         Capital Federal      1547679.0
2020 2         Catamarca              47976.0
2021 4         Santiago Del Estero   115861.0
2017 4         Misiones              103895.0
     3         Córdoba               679929.0

In [40]:
df4_nac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Año                        960 non-null    int64
 1   Trimestre                  960 non-null    int64
 2   Banda ancha fija           960 non-null    int64
 3   Dial up                    960 non-null    int64
 4   Total_x                    960 non-null    int64
 5   Periodo_x                  960 non-null    object
 6   Mbps (Media de bajada)     960 non-null    float64
 7   Trimestre.1                960 non-null    object
 8   Hasta 512 kbps             960 non-null    int64
 9   Entre 512 Kbps y 1 Mbps    960 non-null    int64
 10  Entre 1 Mbps y 6 Mbps      960 non-null    int64
 11  Entre 6 Mbps y 10 Mbps     960 non-null    int64
 12  Entre 10 Mbps y 20 Mbps    960 non-null    int64
 13  Entre 20 Mbps y 30 Mbps    960 non-null    int64
 14  Más de 30 Mbps             960 non-null    int64
 15  OTROS                      960 non-null    int64
 16  Total_y                    960 non-null    int64
 17  Ingresos (miles de pesos)  960 non-null    float64
 18  Periodo_y                  960 non-null    object
 19  Provincia                  960 non-null    object
 20  ADSL                       960 non-null    float64
 21  Cablemodem                 960 non-null    float64
 22  Fibra óptica               960 non-null    float64
 23  Wireless                   960 non-null    float64
 24  Otros                      960 non-null    float64
 25  Total                      960 non-null    float64
dtypes: float64(8), int64(14), object(4)
memory usage: 195.1+ KB

In [42]:
df4_nac = df4_nac.drop(['Periodo_y'], axis = 1)

In [43]:
df4_nac =df4_nac.drop(['Periodo_x','Trimestre'], axis = 1)

In [50]:
df4_nac.sample(10)

,Año,Banda ancha fija,Dial up,Total_x,Mbps (Media de bajada),Trimestre.1,Hasta 512 kbps,Entre 512 Kbps y 1 Mbps,Entre 1 Mbps y 6 Mbps,Entre 6 Mbps y 10 Mbps,Entre 10 Mbps y 20 Mbps,Entre 20 Mbps y 30 Mbps,Más de 30 Mbps,OTROS,Total_y,Ingresos (miles de pesos),Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
812,2015,6902267,32801,6935068,4.788911,Jul-Sept 2015,35030,455777,5087802,701187,539414,13101,20677,0,6852988,5.153739e+06,Santa Fe,337042.0,209673.0,4169.0,4426.0,1428.0,556738.0
453,2019,8938427,21754,8960181,20.330000,Abr-Jun 2019,202790,95980,3444458,871142,1169632,1250366,1677830,247983,8960181,2.074312e+07,Santiago Del Estero,24393.0,64783.0,219.0,2759.0,34600.0,126754.0
509,2018,8320223,26812,8347035,15.360000,Jul-Sept 2018,5675,220589,3401277,859413,1607137,1571692,524777,156475,8347035,1.541098e+07,Córdoba,337620.0,342401.0,15785.0,19213.0,10839.0,725858.0
885,2014,6559172,39324,6598496,4.156888,Oct-Dic 2014,44075,554749,5084556,496251,276254,4371,15229,0,6475485,3.950441e+06,Santiago Del Estero,34110.0,4231.0,19.0,920.0,37.0,39317.0
527,2018,8320223,26812,8347035,15.360000,Jul-Sept 2018,5675,220589,3401277,859413,1607137,1571692,524777,156475,8347035,1.541098e+07,Tucumán,161209.0,9280.0,110.0,252.0,315.0,171166.0
228,2021,10075184,10357,10085541,48.460000,Jul-Sept 2021,40174,41437,2550229,1095772,710122,536364,4948174,163269,10085541,4.299994e+07,Mendoza,91474.0,71247.0,70579.0,21811.0,828.0,255939.0
384,2019,8783053,10128,8793181,28.260000,Oct-Dic 2019,38272,28980,2792307,1046128,851619,1004083,2830746,201046,8793181,2.416925e+07,Buenos Aires,720011.0,2191672.0,669194.0,87111.0,18266.0,3686254.0
370,2020,8802435,9991,8812426,37.520000,Ene-Mar 2020,42550,56170,2649819,1022014,814470,532309,3500882,194212,8812426,2.994622e+07,La Pampa,8553.0,53755.0,13821.0,11295.0,1802.0,89226.0
361,2020,8802435,9991,8812426,37.520000,Ene-Mar 2020,42550,56170,2649819,1022014,814470,532309,3500882,194212,8812426,2.994622e+07,Capital Federal,184494.0,1097635.0,38898.0,3911.0,28556.0,1353494.0
504,2018,8320223,26812,8347035,15.360000,Jul-Sept 2018,5675,220589,3401277,859413,1607137,1571692,524777,156475,8347035,1.541098e+07,Buenos Aires,1435856.0,1929273.0,156382.0,62318.0,26448.0,3610277.0